platform:ios,'7.0'

target 'BuDeJie' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 4.0.0'
pod 'DACircularProgress', '~> 2.3.1'
pod 'pop', '~> 1.0.9'
pod 'POP+MCAnimate', '~> 2.0.1'
pod 'Masonry', '~> 1.0.2'
pod 'YYCategories', '~> 1.0.2'
end
